### ISSUE TITLE
Please Help :  Why i show this error when i tray  import the package in Angular 16

### ISSUE THREAD

**Issue by digylog** [undecaf/zbar-wasm#14]
iwhen i call import { scanImageData } from '@undecaf/zbar-wasm';  and use  return scanImageData(imageData)
        .then(symbols => { ...
I show this error, how can fixe that please 
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
Not allowed to load local resource: file:///D://node_modules/@undecaf/zbar-wasm/dist/zbar.wasm
Aborted([object ProgressEvent]). Build with -sASSERTIONS for more info.
RuntimeError: Aborted([object ProgressEvent]). Build with -sASSERTIONS for more info.
![bug](https://github.com/undecaf/zbar-wasm/assets/106167696/d0acac28-d577-4e97-880f-feff1da6edff)

**Comment by undecaf** [comment]
This is a general issue unrelated to zbar-wasm: your browser does not allow to load `zbar.wasm` as `file:` resource but only as `http:` or `https:` resource. Therefore all your resources including the content of `D:\node_modules` must be served by an HTTP server. Please refer to the Angular documentation in order to find out how to achieve this.

For details, see here: https://support.google.com/chrome/thread/162698059/not-allowed-to-load-local-resource-how-to-fix-this?hl=en
